frame: "map"
#agent_frame: "corrected_base_link"
agent_frame: "base_link"
dist_server_node_name: "dist_server"
path_following_node_name: "path_follower"
occ_map_service: "/occupancy_preprocessing/get_processed_map"
safety_distance: 0.05

sdg:
  min_jbubbles_rad: 0.6
  min_pbubbles_rad: 0.4
  bubbles_dist_offset: 0.0
  knn_checks: 50
  path_subdiv_length: 0.2

strategy:
  #min_frontier_unkn_ratio: 0
  #max_frontier_unkn_ratio: 0
  unkn_occ_range: [40,60]
  #narrowness_cost_d_threshold: 0.
  #max_dist_compromise: 5
  #unknown_max_coverage: 0.3
  frontiers_max_known_ratio: 0.5
  search_dist_increment: 1